apiVersion: v1
kind: ReplicationController
metadata:
  name: news
spec:
  replicas: 2
  selector:
    name: news
  template:
    metadata:
      labels:
        name: news
    spec:
      containers:
      - name: news
        image: monkey.goathorde.org:5000/news:latest
        ports:
        - containerPort: 80
